### ISSUE TITLE
Gazebo topics not getting published when running any SITL simulation

### ISSUE THREAD

**Issue by ganeshrk95** [PX4/PX4-SITL_gazebo-classic#102] opened 2017-05-25 17:51 UTC
I have the latest master clones. When I run the basic IRIS SITL using:

`make posix_sitl_default gazebo`

After the model loads and PX4 shell opens, I did:

`gz topic -l `

I get the following
![screenshot from 2017-05-25 13 20 35](https://cloud.githubusercontent.com/assets/13117114/26462633/937dde82-414f-11e7-9769-73a40ffb70b3.png)

I just cannot echo any iris related topics using:

`gz topic -e /gazebo/default/iris/$NAME `

It returns nothing. I'm developing a Tiltrotor Tricopter model for SITL. I need to view what's going into the motor_speed topics to debug my code. 

I keep getting these warnings but I think this shouldn't cause the topics to not publish anything.
![screenshot from 2017-05-25 13 43 03](https://cloud.githubusercontent.com/assets/13117114/26462822/5533bfb0-4150-11e7-880b-37d570a30752.png)

**Comment by wil3** [comment] 2017-08-11 18:59
I'm actually looking into this right. I was attempting to use pygazebo to control the simulator however when you publish any messages it crashes gzserver. 

`gzserver: /home/wil/workspace/PX4/Firmware/Tools/sitl_gazebo/src/gazebo_imu_plugin.cpp:190: void gazebo::GazeboImuPlugin::addNoise(Eigen::Vector3d*, Eigen::Vector3d*, double): Assertion `dt > 0.0' failed.`

Looking into this closer (at least for my case) the simulation time changes and the assertion fails. Working on a fix now.

**Comment by TSC21** [comment] 2018-01-04 18:26
@ganeshrk95 is this solved to you?

**Comment by ganeshrk95** [comment] 2018-03-21 04:17
Still have this issue and can't figure out what is causing this. Increasing the queue limit doesn't seem to fix this.

**Comment by TSC21** [comment] 2018-05-31 00:14
The problem is this: https://bitbucket.org/osrf/gazebo/issues/1149/echo-topic-with-custom-messages-doesnt. And it seems it is still not fixed. So this is not related with `sitl_gazebo` but rather with Gazebo itself. @ganeshrk95 have you tried a further version, like Gazebo 8 or 9 and check if this is still happens?

**Comment by TSC21** [comment] 2018-05-31 00:18
On the Bitbucket issue it is described to hotfixes for it. But I don't actually think they are worth it if the only thing we want from this is to echo the topics.

**Comment by ganeshrk95** [comment] 2018-06-28 11:18
It did happen with Gazebo 8 if I remember correctly.

**Comment by TSC21** [comment] 2018-10-05 19:43
This is Gazebo internals related, not related to any plugin on the this repository. Closing

**Closed as completed by TSC21** 2018-10-05 19:43 UTC
Labels: question, SITL, gazebo internals
