### ISSUE TITLE
Distance_sensor lost for px4 typhoon_h480

### ISSUE THREAD

**Issue by JethroPhuah** [PX4/PX4-SITL_gazebo-classic#762] opened 2021-05-31 05:38 UTC
Hi all, 

I have been facing this issue for the past 2 weeks and I can't seem to have find a solution around it. I was trying to perform terrain following on my px4 drone in gazebo stimulation however to do so, I require my distance sensor to work. However, whenever I run the typhoon_h480, I am always faced with this error: 

![Screenshot from 2021-05-31 01-37-12](https://user-images.githubusercontent.com/62226668/120145108-060fc100-c1b1-11eb-9407-56875bc01848.png)

I have tried unblacklisting the distance sensor plugin from the px4_pluginlists.yaml file however it seems to introduce new problems so I blacklisted it back. Please advise me on this issue. Thanks in advance!

**Comment by Jaeyoung-Lim** [comment] 2021-05-31 07:08
Closing since this is a duplicate of https://github.com/PX4/PX4-SITL_gazebo/issues/755

**Closed as completed by Jaeyoung-Lim** 2021-05-31 07:08 UTC
